version: "3.8"
services:
  api:
    depends_on:
      - db
    build: .
    image: book_rental:0.2
    environment:
      - DATABASE_HOSTNAME=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=fastapi
    ports:
      - "8000:8000"
  db:
    image: postgres
    container_name: postgres-fastapi
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
