version: "3.8"

networks:
  rental-network:
    driver: bridge

services:
  # api:
  #   depends_on:
  #     - db
  #   build: .
  #   image: book_rental:0.1
  #   env_file:
  #     - .env
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - rental-network
  #   volumes:
  #     - ./:/usr/src/app
  #   command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  db_test:
    image: postgres
    container_name: db_test
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi_testing
    ports:
      - "7878:5432"
    networks:
      - rental-network

volumes:
  db:
    driver: local
