version: "3.8"

networks:
  rental-network:
    driver: bridge

services:
  api:
    depends_on:
      - db
    build: .
    image: book_rental:0.1
    environment:
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - SECRET_KEY=98734n34iu5i3u983489n58989735345jhjkhjkhj3kh534589mc83834589cm
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - SMTPEMAIL=book-rentals121@outlook.com
      - SMTPPASSWORD=Password@121
      - ENVV=fromdockerenv
      - HOSTNAME=db
      - PORT=5432
      - DATABASE_NAME=fastapi
    ports:
      - "8000:8000"
    networks:
      - rental-network
    volumes:
      - ./:/usr/src/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi
    ports:
      - "5432:5432"
    networks:
      - rental-network
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
