version: "3.8"

networks:
  rental-network:
    driver: bridge

services:
  api:
    depends_on:
      - db
    image: abhishekgoswami/book_rental
    environment:
      - HOSTNAME=${HOSTNAME}
      - PORT=${PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - SMTPEMAIL=${SMTPEMAIL}
      - SMTPPASSWORD=${SMTPPASSWORD}
    ports:
      - "8000:8000"
    networks:
      - rental-network
    
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    networks:
      - rental-network
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
