version: "3.8"

services:
  app:
    depends_on:
      - db
      - testing_db
    build: .
    image: abhishekgoswami/book_rental:0.1
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - fastapi_rental-network

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - fastapi_rental-network

  testing_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi_testing
    ports:
      - "5436:5432"
    networks:
      - fastapi_rental-network

volumes:
  db:
    driver: local

networks:
  fastapi_rental-network:
    driver: bridge
