"""updated dueamount coloumn name in rental cart

Revision ID: 7574acbaac9b
Revises: fa37b4f1db85
Create Date: 2023-05-24 15:21:16.805643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7574acbaac9b'
down_revision = 'fa37b4f1db85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('DueAmount', sa.Integer(), nullable=False))
    op.drop_column('rentals', 'OverDue')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('OverDue', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('rentals', 'DueAmount')
    # ### end Alembic commands ###
