"""Added overdue coloumn in RentalCard table

Revision ID: 874466ca92a0
Revises: 897acb8742bd
Create Date: 2023-05-24 15:13:57.694863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '874466ca92a0'
down_revision = '897acb8742bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('OverDue', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rentals', 'OverDue')
    # ### end Alembic commands ###
