"""Added genre to the book

Revision ID: 897acb8742bd
Revises: 3dd791488e07
Create Date: 2023-05-23 14:51:17.499604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '897acb8742bd'
down_revision = '3dd791488e07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('Genre', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'Genre')
    # ### end Alembic commands ###
