"""overdue nullable false in rentalcart table

Revision ID: fa37b4f1db85
Revises: 874466ca92a0
Create Date: 2023-05-24 15:17:13.961992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa37b4f1db85'
down_revision = '874466ca92a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
