name: Build and Deploy code

on: ['push', 'pull_request']

jobs:
  job1:
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      SECRET_KEY: 98734n34iu5i3u983489n58989735345jhjkhjkhj3kh534589mc83834589cm
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
      SMTPEMAIL: book-rentals121@outlook.com
      SMTPPASSWORD: Password@121
      HOSTNAME: db
      PORT: 5432
      DATABASE_NAME: fastapi

    runs-on: ubuntu-latest
    
    steps:

      - name: pulling repo
        uses: actions/checkout@v2

      - name: installing python version 3.10.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6

      - name: update pip
        run: python -m pip install --upgrade pip
      
      - name: installing dependencies
        run: pip install -r requirements.txt 
      
      - name: testing
        run: pytest