name: Build and Deploy code

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  job1:
    environment:
      name: testing
    env:
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
      SMTPEMAIL: ${{ secrets.SMTPEMAIL }}
      SMTPPASSWORD: ${{ secrets.SMTPPASSWORD }}
      HOSTNAME: ${{ secrets.HOSTNAME }}
      PORT: ${{ secrets.PORT }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      TESTING_DB_NAME: ${{ secrets.TESTING_DB_NAME }}
      TESTING_DB_HOST: ${{ secrets.TESTING_DB_HOST }}
      TESTING_DB_PORT: ${{ secrets.TESTING_DB_PORT }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

    runs-on: ubuntu-latest

    steps:
      - name: pulling repo
        uses: actions/checkout@v2

      - name: installing python version 3.10.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6

      - name: update pip
        run: python -m pip install --upgrade pip

      - name: installing dependencies
        run: pip install -r requirements.txt

      - name: testing
        run: |
          docker-compose up -d
          docker ps
          pytest -v -s

      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/book_rental:latest
