name: Build and Deploy code

on: ['push', 'pull_request']

jobs:
  job1:
    
    environment:
      name: testing

    env:
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
      SMTPEMAIL: ${{ secrets.SMTPEMAIL }}
      SMTPPASSWORD: ${{ secrets.SMTPPASSWORD }}
      HOSTNAME: ${{ secrets.HOSTNAME }}
      PORT: ${{ secrets.PORT }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}

    services:
      postgres:
        
        image: postgres
        
        env:
          POSTGRES_USER: ${{ secrets.DATABASE_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}_testing
        
        ports:
          - 7878:5432
        
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    runs-on: ubuntu-latest
    
    steps:

      - name: pulling repo
        uses: actions/checkout@v2

      - name: installing python version 3.10.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6

      - name: update pip
        run: python -m pip install --upgrade pip
      
      - name: installing dependencies
        run: pip install -r requirements.txt 
      
      - name: testing
        run: pytest